harvest:
  ignore:
    - GID OFF - Public Holiday
    - GID OFF - Time Off
projects:
  - id: KPIW-001
    name: Platforma Analityczna dla ING WBAA
    description: Stworzenie platformy do analizowania i przetwarzania dużych zbiorów danych oraz trenowania i serwowania modeli ML
    employee: Michał Lula
    startDate: 2018-09-01
    endDate: 2021-11-05
    harvest:
      - code: ING -  DA & MLOPS
        types:
          - Development
          - Dev/Ops
    interpretationNumber: 611570/I
    results:
      - name: Data Science in a Box
      - name: Generic Ingestion Pipeline
      - name: Kedro project template
      - name: Data Leakage Prevention Service
      - name: Scheduler as a Service
  - name: Data Engine w Allegro.pl
    id: KPIW-002
    description: |
      Synchornizacja danych pomiędzy HDFS i BigQuery. 
      Rozwój platformy do wspomanagania analizy danych, trenowania modeli ML i Generative AI.
      Automatyzacja standardowych przepływów pracy.
      Stworzenie portalu do procesowania danych i zarządzania nimi.
    employee: Michał Lula
    startDate: 2021-11-08
    harvest:
      - code: "[GCP Migration] Kopiowaczka #2"
        types:
          - Development
      - code: "[GCP Migration] General Q4 2021 - Q1 2022"
        types:
          - Development
      - code: "[GCP Migration] General Q2 2022"
        types:
          - Development
      - code: "Allegro - [GCP Migration] General 2022-23"
        types:
          - Development
    interpretationNumber: 611570/I
    results:
      - name: Kopiowaczka
        startDate: 2019-01-02
        endDate: 2019-01-02
      - name: Managed Shared Composer
        startDate: 2019-01-02
        endDate: 2019-01-02
      - name: Data Console
        startDate: 2019-01-02
        endDate: 2019-01-02
wages:
  - from: 2017-03-01
    wage: 120
  - from: 2018-03-01
    wage: 126
  - from: 2019-03-01
    wage: 152
  - from: 2020-03-01
    wage: 160
  - from: 2021-03-01
    wage: 169
  - from: 2021-08-01
    wage: 180
  - from: 2022-04-01
    wage: 220
  - from: 2022-12-01
    wage: 225
  - from: 2023-04-01
    wage: 250
ip_box_records:
  incomes:
    - companyName:
        equals: GETINDATA ADAM KAWA, PIOTR KREWSKI S.C.
    - companyName:
        equals: GetInData Sp. z o. o. Sp. k.
    - companyName:
        equals: GETINDATA Sp. z o.o. Sp. komandytowa
    - companyName:
        equals: GETINDATA POLAND Sp. z o.o.
  costs:
    - description:
        contains: Fundusz Pracy
      category: 'A'
    - description:
        contains: Składka zdrowotna
      category: 'A'
    - description:
        startsWith: Zakup paliwa
      category: 'A'
    - description:
        startsWith: Paliwo
      category: 'A'
    - description:
        startsWith: Koszty pojazdu
      category: 'A'
    - description:
        startsWith: akumulator
      category: 'A'
    - description:
        contains: leasing
      category: 'A'
    - description:
        startsWith: polisa OC
      category: 'A'
    - description:
        startsWith: ubezpieczenie komunikacyjne
      category: 'A'
    - description:
        startsWith: Wydatki związane z komputerem
      category: 'A'
    - description:
        startsWith: Kabel USB c
      category: 'A'
    - description:
        startsWith: WXAD10 adapter strumieniowy
      category: 'A'
    - description:
        startsWith: dysk
      category: 'A'
    - description:
        startsWith: Artykuły biurowe
      category: 'A'
    - description:
        startsWith: Wyposażenie biura
      category: 'A'
    - description:
        startsWith: Satechi
      category: 'A'
    - description:
        startsWith: Laptop
      category: 'A'